from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name="Organization",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=200,unique=True)),("slug",models.SlugField(max_length=100,unique=True)),("is_active",models.BooleanField(default=True)),("created_at",models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="ApiKey",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(default="default",max_length=100)),("prefix",models.CharField(db_index=True,max_length=12)),("key_hash",models.CharField(max_length=64,unique=True)),("is_active",models.BooleanField(default=True)),("created_at",models.DateTimeField(auto_now_add=True)),("last_used_at",models.DateTimeField(blank=True,null=True)),("organization",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="api_keys",to="exchange.organization"))]),
        migrations.CreateModel(name="Observation",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("ip_address",models.GenericIPAddressField()),("reason",models.CharField(choices=[("signup_abuse","Signup abuse"),("spam","Spam"),("scraping","Scraping"),("credential_abuse","Credential abuse"),("payment_fraud","Payment fraud"),("ddos","DDoS"),("other","Other")],default="other",max_length=32)),("first_seen_at",models.DateTimeField()),("last_seen_at",models.DateTimeField()),("expires_at",models.DateTimeField()),("active",models.BooleanField(default=True)),("metadata",models.JSONField(blank=True,default=dict)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("organization",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="observations",to="exchange.organization"))],options={"indexes":[models.Index(fields=["ip_address","active"],name="exchange_ob_ip_addr_idx"),models.Index(fields=["updated_at"],name="exchange_ob_updated_idx"),models.Index(fields=["expires_at"],name="exchange_ob_expires_idx")],"constraints":[models.UniqueConstraint(fields=("organization","ip_address"),name="one_observation_per_org_ip")]})
    ]
